### ISSUE TITLE
PN_Debug_Panel not renamed when creating project

### ISSUE THREAD

**Issue by deshack** [WPBP/generator-wp-plugin-boilerplate-powered#19]
I created a new project with the generator (settings below), but had problems with the Debug Bar integration.

File `/admin/includes/PN_Debug_Panel.php` and class `PN_Debug_Panel` have correctly been renamed, but not calls to that class, so that:

* File `/admin/includes/debug.php`, method `init_panel()`, references `PN_Debug_Panel` instead of `v_Debug_Panel`
* File `/admin/includes/v_Debug_Panel.php`, methods `render()` and `prerender()`, reference `$GLOBALS['PN_Debug']`

Also, the `@package` DocBlock directive in `/admin/includes/debug.php` references `PN_Ad_Admin`.

### Yeoman Generator Settings
```
{
  "name": "Products Showcase for WP",
  "pluginVersion": "1.0.0",
  "author": {
    "name": "Mattia Migliorini",
    "email": "mattia@squeezyweb.com",
    "url": "http://www.squeezyweb.com",
    "copyright": "SqueezyWeb"
  },
  "authorURI": "http://www.squeezyweb.com",
  "publicResources": [],
  "activateDeactivate": [
    "Activate Method",
    "Deactivate Method"
  ],
  "adminPage": false,
  "modules": [
    "CPT_Core",
    "CPT_Columns",
    "Taxonomy_Core",
    "Template system (like WooCommerce)",
    "Language function support (WPML/Ceceppa Multilingua/Polylang)",
    "Freemius SDK"
  ],
  "snippet": [
    "Support Dashboard At Glance Widget for CPT",
    "Support Dashboard Activity Widget for CPT",
    "Debug system (Debug Bar support)",
    "Add body class",
    "CPTs on search box",
    "Custom action",
    "Custom filter",
    "Custom shortcode"
  ],
  "git": true,
  "cleanFolder": true,
  "coffeescript": false,
  "unittest": true,
  "saveSettings": true
}
```

**Comment by Mte90** [comment]
I am thinking on the next major release of the boilerplate with a composer based solution but this will be a problem also for that part because this is an internal library of the project.

**Comment by deshack** [comment]
Composer would be great!

**Comment by Mte90** [comment]
The 2.0 have the debug library as composer dependence so this will be not required anymore
